const cartActionType = {
    "GET_CART_BY_USER_ID_SUCCESS": "GET_PRODUCT_CART_BY_USER_ID_SUCCESS",
    "ADD_PRODUCT_INTO_CART_SUCCESS": "ADD_PRODUCT_INTO_CART_SUCCESS",
    "UPDATE_CART_SUCCESS": "UPDATE_CART_SUCCESS",
  }
  
  export default cartActionType